spring:
  application:
    name: 31-SpringBootActuator-APP-13
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'beans'
         
       
  endpoint:
    shutdown:
      enabled: true